# Generated by Django 2.2.19 on 2022-09-27 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_url', models.CharField(max_length=128, unique=True)),
                ('full_url', models.TextField(max_length=1024)),
            ],
        ),
    ]
